### ISSUE TITLE
S3cmd ls gives Problem: BadStatusLine: ''

### ISSUE THREAD

**Issue by naiduasn** [ianbytchek/docker-riak-cs#11]
Invoked as: /usr/local/bin/s3cmd ls s3://foo
Problem: BadStatusLine: ''
S3cmd:   1.6.1
python:   2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
environment LANG=None

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2996, in <module>
  File "/usr/local/lib/python2.7/site-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2915, in main
  File "/usr/local/lib/python2.7/site-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 137, in cmd_ls
  File "/usr/local/lib/python2.7/site-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 170, in subcmd_bucket_list
  File "build/bdist.macosx-10.11-x86_64/egg/S3/S3.py", line 327, in bucket_list
    for truncated, dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params, limit):
  File "build/bdist.macosx-10.11-x86_64/egg/S3/S3.py", line 358, in bucket_list_streaming
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params, max_keys)
  File "build/bdist.macosx-10.11-x86_64/egg/S3/S3.py", line 389, in bucket_list_noparse
    response = self.send_request(request)
  File "build/bdist.macosx-10.11-x86_64/egg/S3/S3.py", line 1235, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "build/bdist.macosx-10.11-x86_64/egg/S3/ConnMan.py", line 249, in get
    conn.c.connect()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 839, in connect
    self._tunnel()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 811, in _tunnel
    (version, code, message) = response._read_status()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

**Comment by iby** [comment]
@naiduasn hey. I've re-run the ci build with s3cmd tests, they all pass as expected – https://circleci.com/gh/ianbytchek/docker-riak-cs/196. I haven't looked into this project for awhile nor touched s3cmd recently, but the fact that you're getting an exception is most likely due to a bug in s3cmd, otherwise you'd be getting a warning or something more informative.

I suggest pulling the default image and running tests locally to see what happens – https://github.com/ianbytchek/docker-riak-cs/blob/master/build/ci/script/test.sh.  If they fail, then the problem is most likely in your local s3cmd copy. If they pass, perhaps you've added something into the bucket that makes s3cmd to choke, maybe some unicode keys or something unexpected? Let me know if you can narrow down the issue to this image, otherwise guys at s3cmd project should be able to help more with this.

**Comment by naiduasn** [comment]
Thanks @ianbytchek. It could be probably with s3cmd copy. I will analyse.
Meanwhile, do you remember which version of s3cmd you used to do this earlier?

**Comment by naiduasn** [comment]
Working fine with s3cmd=1.5.2.
